### ISSUE TITLE
SDNEXT: no pop-up window on right-click

### ISSUE THREAD

**Issue by RGX650** [nihedon/sd-webui-weight-helper#1] opened 2023-12-27 06:23 UTC
SDNEXT: no pop-up window on right-click

Browser: OperaGX
i authorized javascript, windows management, removed in-built ad-blocker.

thanks!

**Comment by nihedon** [comment] 2023-12-29 15:19
Thank you for reporting the issue.
I tested SDNEXT using OperaGX but couldn't replicate the problem; the context menu appeared as expected.
(However, I did notice a bug where the context menu doesn't close, and I'll address that in an upcoming fix.)

To investigate further, could you please check for any errors in the browser's debug console (Ctrl+Shift+C)?
This additional information will help us identify and resolve the issue more effectively.

**Comment by RGX650** [comment] 2023-12-30 00:24
Okay, so i tried to investigate a bit too:
i reinstall lora block weight extension and weight helper extension. 
I also deactivate the extension devdark https://github.com/carakan/stable-diffusion-webui-devdark
this extension is applying a custom ui style.

I think the problem comes from the devdark extension. cuold you have a look? Thanks !

**Comment by nihedon** [comment] 2023-12-31 08:41
Thanks for the additional info.

Hmmm...
I installed the "devdark" extension and retested, but still could not reproduce the problem...
*This extension only overwrites the stylesheet and should have no other effect.
![sdnext-operagx](https://github.com/nihedon/sd-webui-weight-helper/assets/66118290/a00fb94d-6cfa-4675-938d-6b102c7f7f2a)

Please let me check the following

- Are you using Windows?
  It is unlikely, but there may be an OS-dependent factor: we have only tested it on Windows, so it may not work on Linux or Mac.
- Are you right-clicking on the word "<lora:sample:1>"? Also, is the text not in the selected state when you do so?
  If the text is in the selected state, the default context menu of the browser will be displayed.

Sorry I can't help you with this.
Please let us know if you have additional information and we will respond.

**Comment by NaokiSato102** [comment] 2024-01-07 22:13
Not just in SDNEXT, but also in the normal SDWebUI, it doesn't appear.  
The active SD extensions are as shown in the attached image.  
Please refer to the appendix for others.  
The presence or absence of Chrome extensions seems irrelevant,  
given that the same issue occurred even when I tried it in the guest environment.

However, when I right-click on the string "LoRa,"  
the usual right-click menu does not appear, though the popup does not either.  
It seems that only the display of the custom popup is not working (or it appears for a moment and then disappears?).

![FireShot Capture 079 - Stable Diffusion - 127 0 0 1](https://github.com/nihedon/sd-webui-weight-helper/assets/27545766/e269e0c2-b028-4048-83d0-d697cf0a692f)



# Appendix

```json
{
  "date": "Mon Jan  8 07:09:24 2024",
  "timestamp": "07:09:24",
  "uptime": "Mon Jan  8 07:02:26 2024",
  "version": {
    "app": "stable-diffusion-webui.git",
    "updated": "2023-12-16",
    "hash": "cf2772fa",
    "url": "https://github.com/AUTOMATIC1111/stable-diffusion-webui.git/tree/HEAD"
  },
  "torch": "2.1.0+cu121 autocast  half",
  "gpu": {
    "device": "NVIDIA GeForce RTX 3060 (1) (sm_90) (8, 6)",
    "cuda": "12.1",
    "cudnn": 8801,
    "driver": "546.01"
  },
  "state": {
    "started": "Mon Jan  8 07:09:24 2024",
    "step": "0 / 0",
    "jobs": "0 / 0",
    "flags": "",
    "job": "",
    "text-info": ""
  },
  "memory": {
    "ram": {
      "free": 57.11,
      "used": 6.75,
      "total": 63.86
    },
    "gpu": {
      "free": 8.4,
      "used": 3.6,
      "total": 12
    },
    "gpu-active": {
      "current": 2.18,
      "peak": 5.14
    },
    "gpu-allocated": {
      "current": 2.18,
      "peak": 5.14
    },
    "gpu-reserved": {
      "current": 2.56,
      "peak": 5.4
    },
    "gpu-inactive": {
      "current": 0.38,
      "peak": 0.6
    },
    "events": {
      "retries": 0,
      "oom": 0
    },
    "utilization": 0
  },
  "optimizations": [
    "none"
  ],
  "libs": {
    "xformers": "0.0.20",
    "diffusers": "0.15.0",
    "transformers": "4.30.2"
  },
  "repos": {
    "Stable Diffusion": "[cf1d67a] 2023-03-25",
    "Stable Diffusion XL": "[45c443b] 2023-07-26",
    "CodeFormer": "[c5b4593] 2022-09-09",
    "BLIP": "[48211a1] 2022-06-07",
    "k_diffusion": "[ab527a9] 2023-08-12"
  },
  "device": {
    "active": "cuda",
    "dtype": "torch.float16",
    "vae": "torch.float32",
    "unet": "torch.float16"
  },
  "model": {
    "configured": {
      "base": "HimawariMix_v8_0.safetensors [b334cb73d8]",
      "refiner": "",
      "vae": "None"
    },
    "loaded": {
      "base": "D:\\Programs_D\\_MachineLearning\\StableDiffusionModels\\Online\\CheckPoint\\HimawariMix_v8_0.safetensors",
      "refiner": "",
      "vae": null
    }
  },
  "schedulers": [
    "DDIM",
    "DPM adaptive",
    "DPM fast",
    "DPM++ 2M",
    "DPM++ 2M Karras",
    "DPM++ 2M SDE",
    "DPM++ 2M SDE Exponential",
    "DPM++ 2M SDE Heun",
    "DPM++ 2M SDE Heun Exponential",
    "DPM++ 2M SDE Heun Karras",
    "DPM++ 2M SDE Karras",
    "DPM++ 2S a",
    "DPM++ 2S a Karras",
    "DPM++ 3M SDE",
    "DPM++ 3M SDE Exponential",
    "DPM++ 3M SDE Karras",
    "DPM++ SDE",
    "DPM++ SDE Karras",
    "DPM2",
    "DPM2 Karras",
    "DPM2 a",
    "DPM2 a Karras",
    "Euler",
    "Euler a",
    "Heun",
    "LMS",
    "LMS Karras",
    "PLMS",
    "Restart",
    "UniPC"
  ],
  "extensions": [
    "Generate-TransparentIMG (enabled)",
    "LDSR (enabled builtin)",
    "Lora (enabled builtin)",
    "PBRemTools (disabled)",
    "ScuNET (enabled builtin)",
    "Stable-Diffusion-WebUI-TensorRT (disabled)",
    "Stable-Diffusion-Webui-Civitai-Helper (enabled)",
    "SwinIR (enabled builtin)",
    "a1111-sd-webui-tagcomplete (enabled)",
    "adetailer (enabled)",
    "canvas-zoom (enabled)",
    "canvas-zoom-and-pan (enabled builtin)",
    "extra-options-section (enabled builtin)",
    "hypertile (enabled builtin)",
    "mobile (enabled builtin)",
    "novelai-2-local-prompt (enabled)",
    "openpose-editor (enabled)",
    "prompt-bracket-checker (enabled builtin)",
    "prompt_translator (disabled)",
    "sd-colab-commands-browser (disabled)",
    "sd-dynamic-prompts (enabled)",
    "sd-extension-system-info (enabled)",
    "sd-webui-animatediff (disabled)",
    "sd-webui-ar (enabled)",
    "sd-webui-bilingual-localization (enabled)",
    "sd-webui-controlnet (enabled)",
    "sd-webui-cutoff (disabled)",
    "sd-webui-deepdanbooru-object-recognition (enabled)",
    "sd-webui-deepdanbooru-tag2folder (enabled)",
    "sd-webui-enable-checker (enabled)",
    "sd-webui-freeu (enabled)",
    "sd-webui-llul (disabled)",
    "sd-webui-lora-block-weight (enabled)",
    "sd-webui-lycoris-sorter (enabled)",
    "sd-webui-model-converter (enabled)",
    "sd-webui-negpip (enabled)",
    "sd-webui-prompt-history (enabled)",
    "sd-webui-regional-prompter (enabled)",
    "sd-webui-tinycards (enabled)",
    "sd-webui-txt-img-to-3d-model (enabled)",
    "sd-webui-weight-helper (enabled)",
    "sd_extension-prompt_formatter (enabled)",
    "sdweb-merge-block-weighted-gui (enabled)",
    "sdwebui-close-confirmation-dialogue (enabled)",
    "stable-diffusion-webui-localization-ja_JP (enabled)",
    "stable-diffusion-webui-pixelization (enabled)"
  ],
  "platform": {
    "arch": "AMD64",
    "cpu": "Intel64 Family 6 Model 167 Stepping 1, GenuineIntel",
    "system": "Windows",
    "release": "Windows-10-10.0.19045-SP0",
    "python": "3.10.9"
  },
  "crossattention": "xformers",
  "backend": "",
  "pipeline": ""
}
```

**Comment by NaokiSato102** [comment] 2024-01-07 22:16
The Appendix was generated by the sd-extension-system-info.  
I believe it would be helpful for verifying compatibility issues if others also provide similar information.

**Comment by nihedon** [comment] 2024-01-10 11:58
@NaokiSato102 

I've tested by installing all the extensions shown in the screenshot to see if the issue could be reproduced, but it still didn't occur... The context menu displayed correctly without any issues.

If you could check for JavaScript errors using the browser's debugging tools, we might be able to identify the root cause. If you're using Google Chrome, you can launch the debugging tools by pressing the F12 key. In the Console tab of the debugging tools, you can check if any errors are being reported. Could you please verify this for further investigation?

**Comment by NaokiSato102** [comment] 2024-01-10 13:29
F12 with guest acco chrome
```
contentscript.js:132 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated
 (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. 
 Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. 
 Consider using MutationObserver instead.
（匿名） @ contentscript.js:132
他 1 件のフレームを表示
一部表示
127.0.0.1/:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'blocks')
    at chrome-extension://comoodengbhchaeglcgaaokhaicgngoo/src/cs/app.js:1:357
127.0.0.1/:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
civitai_helper.js?1699883422.1239884:939 Running Stable-Diffusion-Webui-Civitai-Helper on Gradio Version: 3.23.0
txt-img-to-3d-mode.js?1704039689.2539837:1 [Txt/Img to 3D Model] loading...

Blocks.svelte:258 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:258:11
    at Array.forEach (<anonymous>)
    at qe (Blocks.svelte:256:9)
    at Blocks.svelte:376:7
weight_helper.js?1704616628.868447:121 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at #loadLbwPresets (weight_helper.js?1704616628.868447:121:27)
    at new WeightContextMenu (weight_helper.js?1704616628.868447:92:29)
    at HTMLTextAreaElement.<anonymous> (weight_helper.js?1704616628.868447:611:34)
```

**Comment by nihedon** [comment] 2024-01-10 16:28
@NaokiSato102 

Thank you, this console log is incredibly helpful!
It is likely due to the presence of blank lines in the preset for LoRA Block Weight.
For now, I have attempted to correct it to ensure that it functions properly even if blank lines are included.
Please update to the latest version and check.

**Comment by nihedon** [comment] 2024-03-02 09:28
@RGX650 
It seems to be resolved, so I'll go ahead and close this.
Thank you for the report!

**Closed by nihedon** 2024-03-02 09:28 UTC

**Comment by RGX650** [comment] 2024-04-24 13:01
Sorry for very late reply !!! Work perfectly ;) Well done !
